export const FETCH_EXTENSIONS_REQUEST = 'admin/extensions/FETCH_EXTENSIONS_REQUEST'
export const FETCH_EXTENSIONS_SUCCESS = 'admin/extensions/FETCH_EXTENSIONS_SUCCESS'
export const FETCH_EXTENSIONS_FAILURE = 'admin/extensions/FETCH_EXTENSIONS_FAILURE'

export const UPLOAD_EXTENSION_REQUEST = 'admin/extensions/UPLOAD_EXTENSION_REQUEST'
export const UPLOAD_EXTENSION_SUCCESS = 'admin/extensions/UPLOAD_EXTENSION_SUCCESS'
export const UPLOAD_EXTENSION_FAILURE = 'admin/extensions/UPLOAD_EXTENSION_FAILURE'

export const UPDATE_EXTENSION_REQUEST = 'admin/extensions/UPDATE_EXTENSION_REQUEST'
export const UPDATE_EXTENSION_SUCCESS = 'admin/extensions/UPDATE_EXTENSION_SUCCESS'
export const UPDATE_EXTENSION_FAILURE = 'admin/extensions/UPDATE_EXTENSION_FAILURE'

export const DELETE_EXTENSION_REQUEST = 'admin/extensions/DELETE_EXTENSION_REQUEST'
export const DELETE_EXTENSION_SUCCESS = 'admin/extensions/DELETE_EXTENSION_SUCCESS'
export const DELETE_EXTENSION_FAILURE = 'admin/extensions/DELETE_EXTENSION_FAILURE'
