export const FETCH_HEALTH_STATUSES_REQUEST = 'FETCH_HEALTH_STATUSES_REQUEST';
export const FETCH_HEALTH_STATUSES_SUCCESS = 'FETCH_HEALTH_STATUSES_SUCCESS';
export const FETCH_HEALTH_STATUSES_FAILURE = 'FETCH_HEALTH_STATUSES_FAILURE';

export const RUN_HEALTH_CHECK_REQUEST = 'RUN_HEALTH_CHECK_REQUEST';
export const RUN_HEALTH_CHECK_SUCCESS = 'RUN_HEALTH_CHECK_SUCCESS';
export const RUN_HEALTH_CHECK_FAILURE = 'RUN_HEALTH_CHECK_FAILURE';
