export const FETCH_PRICING_PACKAGES_REQUEST = 'pricing/FETCH_PRICING_PACKAGES_REQUEST'
export const FETCH_PRICING_PACKAGES_SUCCESS = 'pricing/FETCH_PRICING_PACKAGES_SUCCESS'
export const FETCH_PRICING_PACKAGES_FAILURE = 'pricing/FETCH_PRICING_PACKAGES_FAILURE'

export const SUBSCRIBE_TO_PLAN_REQUEST = 'pricing/SUBSCRIBE_TO_PLAN_REQUEST'
export const SUBSCRIBE_TO_PLAN_SUCCESS = 'pricing/SUBSCRIBE_TO_PLAN_SUCCESS'
export const SUBSCRIBE_TO_PLAN_FAILURE = 'pricing/SUBSCRIBE_TO_PLAN_FAILURE'

export const CLEAR_SUBSCRIPTION_RESULT = 'pricing/CLEAR_SUBSCRIPTION_RESULT'
