export const FETCH_ADMIN_USER_DETAILS_REQUEST = 'FETCH_ADMIN_USER_DETAILS_REQUEST';
export const FETCH_ADMIN_USER_DETAILS_SUCCESS = 'FETCH_ADMIN_USER_DETAILS_SUCCESS';
export const FETCH_ADMIN_USER_DETAILS_FAILURE = 'FETCH_ADMIN_USER_DETAILS_FAILURE';
