export const FETCH_ADMIN_STATS_REQUEST = 'FETCH_ADMIN_STATS_REQUEST';
export const FETCH_ADMIN_STATS_SUCCESS = 'FETCH_ADMIN_STATS_SUCCESS';
export const FETCH_ADMIN_STATS_FAILURE = 'FETCH_ADMIN_STATS_FAILURE';

export const FETCH_ADMIN_USERS_REQUEST = 'FETCH_ADMIN_USERS_REQUEST';
export const FETCH_ADMIN_USERS_SUCCESS = 'FETCH_ADMIN_USERS_SUCCESS';
export const FETCH_ADMIN_USERS_FAILURE = 'FETCH_ADMIN_USERS_FAILURE';

export const UPDATE_ADMIN_USER_REQUEST = 'UPDATE_ADMIN_USER_REQUEST';
export const UPDATE_ADMIN_USER_SUCCESS = 'UPDATE_ADMIN_USER_SUCCESS';
export const UPDATE_ADMIN_USER_FAILURE = 'UPDATE_ADMIN_USER_FAILURE';

export const DELETE_ADMIN_USER_REQUEST = 'DELETE_ADMIN_USER_REQUEST';
export const DELETE_ADMIN_USER_SUCCESS = 'DELETE_ADMIN_USER_SUCCESS';
export const DELETE_ADMIN_USER_FAILURE = 'DELETE_ADMIN_USER_FAILURE';

// ── Bot Management ─────────────────────────────────────────────────────────────
export const FETCH_ADMIN_BOTS_REQUEST = 'FETCH_ADMIN_BOTS_REQUEST';
export const FETCH_ADMIN_BOTS_SUCCESS = 'FETCH_ADMIN_BOTS_SUCCESS';
export const FETCH_ADMIN_BOTS_FAILURE = 'FETCH_ADMIN_BOTS_FAILURE';

export const UPDATE_ADMIN_BOT_REQUEST = 'UPDATE_ADMIN_BOT_REQUEST';
export const UPDATE_ADMIN_BOT_SUCCESS = 'UPDATE_ADMIN_BOT_SUCCESS';
export const UPDATE_ADMIN_BOT_FAILURE = 'UPDATE_ADMIN_BOT_FAILURE';


export const DELETE_ADMIN_BOT_REQUEST = 'DELETE_ADMIN_BOT_REQUEST';
export const DELETE_ADMIN_BOT_SUCCESS = 'DELETE_ADMIN_BOT_SUCCESS';
export const DELETE_ADMIN_BOT_FAILURE = 'DELETE_ADMIN_BOT_FAILURE';

// ── Wallet Management ────────────────────────────────────────────────────────
export const FETCH_ADMIN_WALLETS_REQUEST = 'FETCH_ADMIN_WALLETS_REQUEST';
export const FETCH_ADMIN_WALLETS_SUCCESS = 'FETCH_ADMIN_WALLETS_SUCCESS';
export const FETCH_ADMIN_WALLETS_FAILURE = 'FETCH_ADMIN_WALLETS_FAILURE';

export const CREATE_ADMIN_WALLET_REQUEST = 'CREATE_ADMIN_WALLET_REQUEST';
export const CREATE_ADMIN_WALLET_SUCCESS = 'CREATE_ADMIN_WALLET_SUCCESS';
export const CREATE_ADMIN_WALLET_FAILURE = 'CREATE_ADMIN_WALLET_FAILURE';

export const DELETE_ADMIN_WALLET_REQUEST = 'DELETE_ADMIN_WALLET_REQUEST';
export const DELETE_ADMIN_WALLET_SUCCESS = 'DELETE_ADMIN_WALLET_SUCCESS';
export const DELETE_ADMIN_WALLET_FAILURE = 'DELETE_ADMIN_WALLET_FAILURE';

// ── Email Templates ──────────────────────────────────────────────────────────
export const FETCH_EMAIL_TEMPLATES_REQUEST = 'FETCH_EMAIL_TEMPLATES_REQUEST';
export const FETCH_EMAIL_TEMPLATES_SUCCESS = 'FETCH_EMAIL_TEMPLATES_SUCCESS';
export const FETCH_EMAIL_TEMPLATES_FAILURE = 'FETCH_EMAIL_TEMPLATES_FAILURE';

export const CREATE_EMAIL_TEMPLATE_REQUEST = 'CREATE_EMAIL_TEMPLATE_REQUEST';
export const CREATE_EMAIL_TEMPLATE_SUCCESS = 'CREATE_EMAIL_TEMPLATE_SUCCESS';
export const CREATE_EMAIL_TEMPLATE_FAILURE = 'CREATE_EMAIL_TEMPLATE_FAILURE';

export const UPDATE_EMAIL_TEMPLATE_REQUEST = 'UPDATE_EMAIL_TEMPLATE_REQUEST';
export const UPDATE_EMAIL_TEMPLATE_SUCCESS = 'UPDATE_EMAIL_TEMPLATE_SUCCESS';
export const UPDATE_EMAIL_TEMPLATE_FAILURE = 'UPDATE_EMAIL_TEMPLATE_FAILURE';

export const DELETE_EMAIL_TEMPLATE_REQUEST = 'DELETE_EMAIL_TEMPLATE_REQUEST';
export const DELETE_EMAIL_TEMPLATE_SUCCESS = 'DELETE_EMAIL_TEMPLATE_SUCCESS';
export const DELETE_EMAIL_TEMPLATE_FAILURE = 'DELETE_EMAIL_TEMPLATE_FAILURE';

