export const FETCH_DASHBOARD_DATA_REQUEST = 'FETCH_DASHBOARD_DATA_REQUEST';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_FAILURE = 'FETCH_DASHBOARD_DATA_FAILURE';

export const GENERATE_KEY_REQUEST = 'GENERATE_KEY_REQUEST';
export const GENERATE_KEY_SUCCESS = 'GENERATE_KEY_SUCCESS';
export const GENERATE_KEY_FAILURE = 'GENERATE_KEY_FAILURE';

export const DELETE_KEY_REQUEST = 'DELETE_KEY_REQUEST';
export const DELETE_KEY_SUCCESS = 'DELETE_KEY_SUCCESS';
export const DELETE_KEY_FAILURE = 'DELETE_KEY_FAILURE';

export const REGENERATE_KEY_REQUEST = 'REGENERATE_KEY_REQUEST';
export const REGENERATE_KEY_SUCCESS = 'REGENERATE_KEY_SUCCESS';
export const REGENERATE_KEY_FAILURE = 'REGENERATE_KEY_FAILURE';

export const TOGGLE_AUTO_RENEW_REQUEST = 'TOGGLE_AUTO_RENEW_REQUEST';
export const TOGGLE_AUTO_RENEW_SUCCESS = 'TOGGLE_AUTO_RENEW_SUCCESS';
export const TOGGLE_AUTO_RENEW_FAILURE = 'TOGGLE_AUTO_RENEW_FAILURE';

export const CANCEL_PACKAGE_REQUEST = 'CANCEL_PACKAGE_REQUEST';
export const CANCEL_PACKAGE_SUCCESS = 'CANCEL_PACKAGE_SUCCESS';
export const CANCEL_PACKAGE_FAILURE = 'CANCEL_PACKAGE_FAILURE';

export const FETCH_ACTIVITIES_REQUEST = 'FETCH_ACTIVITIES_REQUEST';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_FAILURE = 'FETCH_ACTIVITIES_FAILURE';

export const UPDATE_USER_BALANCE = 'UPDATE_USER_BALANCE';

export const FETCH_EXTENSIONS_REQUEST = 'FETCH_EXTENSIONS_REQUEST';
export const FETCH_EXTENSIONS_SUCCESS = 'FETCH_EXTENSIONS_SUCCESS';
export const FETCH_EXTENSIONS_FAILURE = 'FETCH_EXTENSIONS_FAILURE';

export const FETCH_OFFERS_REQUEST = 'FETCH_OFFERS_REQUEST';
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';
export const FETCH_OFFERS_FAILURE = 'FETCH_OFFERS_FAILURE';
