export const FETCH_CACHE_SETTINGS_REQUEST = 'admin/cache-control/FETCH_CACHE_SETTINGS_REQUEST'
export const FETCH_CACHE_SETTINGS_SUCCESS = 'admin/cache-control/FETCH_CACHE_SETTINGS_SUCCESS'
export const FETCH_CACHE_SETTINGS_FAILURE = 'admin/cache-control/FETCH_CACHE_SETTINGS_FAILURE'

export const UPDATE_CACHE_SETTING_REQUEST = 'admin/cache-control/UPDATE_CACHE_SETTING_REQUEST'
export const UPDATE_CACHE_SETTING_SUCCESS = 'admin/cache-control/UPDATE_CACHE_SETTING_SUCCESS'
export const UPDATE_CACHE_SETTING_FAILURE = 'admin/cache-control/UPDATE_CACHE_SETTING_FAILURE'
