export const FETCH_SOLUTIONS_REQUEST = 'admin/solutions/FETCH_SOLUTIONS_REQUEST'
export const FETCH_SOLUTIONS_SUCCESS = 'admin/solutions/FETCH_SOLUTIONS_SUCCESS'
export const FETCH_SOLUTIONS_FAILURE = 'admin/solutions/FETCH_SOLUTIONS_FAILURE'

export const DELETE_SOLUTION_REQUEST = 'admin/solutions/DELETE_SOLUTION_REQUEST'
export const DELETE_SOLUTION_SUCCESS = 'admin/solutions/DELETE_SOLUTION_SUCCESS'
export const DELETE_SOLUTION_FAILURE = 'admin/solutions/DELETE_SOLUTION_FAILURE'

export const CLEAR_ALL_SOLUTIONS_REQUEST = 'admin/solutions/CLEAR_ALL_SOLUTIONS_REQUEST'
export const CLEAR_ALL_SOLUTIONS_SUCCESS = 'admin/solutions/CLEAR_ALL_SOLUTIONS_SUCCESS'
export const CLEAR_ALL_SOLUTIONS_FAILURE = 'admin/solutions/CLEAR_ALL_SOLUTIONS_FAILURE'
