export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE';

export const VERIFY_EMAIL_REQUEST = 'auth/VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'auth/VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'auth/VERIFY_EMAIL_FAILURE';

export const RESEND_VERIFICATION_REQUEST = 'auth/RESEND_VERIFICATION_REQUEST';
export const RESEND_VERIFICATION_SUCCESS = 'auth/RESEND_VERIFICATION_SUCCESS';
export const RESEND_VERIFICATION_FAILURE = 'auth/RESEND_VERIFICATION_FAILURE';

export const GET_CURRENT_USER_REQUEST = 'auth/GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'auth/GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'auth/GET_CURRENT_USER_FAILURE';

export const RESET_AUTH_STATE = 'auth/RESET_AUTH_STATE';

// Login / OTP
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';

export const VERIFY_OTP_REQUEST = 'auth/VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'auth/VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'auth/VERIFY_OTP_FAILURE';

export const RESEND_OTP_REQUEST = 'auth/RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'auth/RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'auth/RESEND_OTP_FAILURE';

export const GOOGLE_LOGIN_REQUEST = 'auth/GOOGLE_LOGIN_REQUEST';
export const GOOGLE_LOGIN_SUCCESS = 'auth/GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAILURE = 'auth/GOOGLE_LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'auth/LOGOUT_FAILURE';
