export const FETCH_CRYPTO_CONFIG_REQUEST = 'FETCH_CRYPTO_CONFIG_REQUEST';
export const FETCH_CRYPTO_CONFIG_SUCCESS = 'FETCH_CRYPTO_CONFIG_SUCCESS';
export const FETCH_CRYPTO_CONFIG_FAILURE = 'FETCH_CRYPTO_CONFIG_FAILURE';

export const FETCH_CRYPTO_PRICE_REQUEST = 'FETCH_CRYPTO_PRICE_REQUEST';
export const FETCH_CRYPTO_PRICE_SUCCESS = 'FETCH_CRYPTO_PRICE_SUCCESS';
export const FETCH_CRYPTO_PRICE_FAILURE = 'FETCH_CRYPTO_PRICE_FAILURE';

export const RECORD_DEPOSIT_REQUEST = 'RECORD_DEPOSIT_REQUEST';
export const RECORD_DEPOSIT_SUCCESS = 'RECORD_DEPOSIT_SUCCESS';
export const RECORD_DEPOSIT_FAILURE = 'RECORD_DEPOSIT_FAILURE';

export const FETCH_DEPOSIT_ADDRESS_REQUEST = 'FETCH_DEPOSIT_ADDRESS_REQUEST';
export const FETCH_DEPOSIT_ADDRESS_SUCCESS = 'FETCH_DEPOSIT_ADDRESS_SUCCESS';
export const FETCH_DEPOSIT_ADDRESS_FAILURE = 'FETCH_DEPOSIT_ADDRESS_FAILURE';

export const START_DEPOSIT_POLLING = 'START_DEPOSIT_POLLING';
export const STOP_DEPOSIT_POLLING = 'STOP_DEPOSIT_POLLING';
export const CHECK_INCOMING_DEPOSITS_REQUEST = 'CHECK_INCOMING_DEPOSITS_REQUEST';
export const CHECK_INCOMING_DEPOSITS_SUCCESS = 'CHECK_INCOMING_DEPOSITS_SUCCESS';
export const CHECK_INCOMING_DEPOSITS_FAILURE = 'CHECK_INCOMING_DEPOSITS_FAILURE';
