export const FETCH_OBJECT_CLASSES_REQUEST = 'FETCH_OBJECT_CLASSES_REQUEST';
export const FETCH_OBJECT_CLASSES_SUCCESS = 'FETCH_OBJECT_CLASSES_SUCCESS';
export const FETCH_OBJECT_CLASSES_FAILURE = 'FETCH_OBJECT_CLASSES_FAILURE';

export const CREATE_OBJECT_CLASS_REQUEST = 'CREATE_OBJECT_CLASS_REQUEST';
export const CREATE_OBJECT_CLASS_SUCCESS = 'CREATE_OBJECT_CLASS_SUCCESS';
export const CREATE_OBJECT_CLASS_FAILURE = 'CREATE_OBJECT_CLASS_FAILURE';

export const UPDATE_OBJECT_CLASS_REQUEST = 'UPDATE_OBJECT_CLASS_REQUEST';
export const UPDATE_OBJECT_CLASS_SUCCESS = 'UPDATE_OBJECT_CLASS_SUCCESS';
export const UPDATE_OBJECT_CLASS_FAILURE = 'UPDATE_OBJECT_CLASS_FAILURE';

export const DELETE_OBJECT_CLASS_REQUEST = 'DELETE_OBJECT_CLASS_REQUEST';
export const DELETE_OBJECT_CLASS_SUCCESS = 'DELETE_OBJECT_CLASS_SUCCESS';
export const DELETE_OBJECT_CLASS_FAILURE = 'DELETE_OBJECT_CLASS_FAILURE';
