export const FETCH_KOLOTI_CACHE_REQUEST = 'FETCH_KOLOTI_CACHE_REQUEST';
export const FETCH_KOLOTI_CACHE_SUCCESS = 'FETCH_KOLOTI_CACHE_SUCCESS';
export const FETCH_KOLOTI_CACHE_FAILURE = 'FETCH_KOLOTI_CACHE_FAILURE';

export const DELETE_KOLOTI_CACHE_REQUEST = 'DELETE_KOLOTI_CACHE_REQUEST';
export const DELETE_KOLOTI_CACHE_SUCCESS = 'DELETE_KOLOTI_CACHE_SUCCESS';
export const DELETE_KOLOTI_CACHE_FAILURE = 'DELETE_KOLOTI_CACHE_FAILURE';

export const UPDATE_KOLOTI_CACHE_ANSWER_REQUEST = 'UPDATE_KOLOTI_CACHE_ANSWER_REQUEST';
export const UPDATE_KOLOTI_CACHE_ANSWER_SUCCESS = 'UPDATE_KOLOTI_CACHE_ANSWER_SUCCESS';
export const UPDATE_KOLOTI_CACHE_ANSWER_FAILURE = 'UPDATE_KOLOTI_CACHE_ANSWER_FAILURE';

// Bot Endpoints
export const FETCH_BOT_ENDPOINTS_REQUEST = 'FETCH_BOT_ENDPOINTS_REQUEST';
export const FETCH_BOT_ENDPOINTS_SUCCESS = 'FETCH_BOT_ENDPOINTS_SUCCESS';
export const FETCH_BOT_ENDPOINTS_FAILURE = 'FETCH_BOT_ENDPOINTS_FAILURE';

export const CREATE_BOT_ENDPOINT_REQUEST = 'CREATE_BOT_ENDPOINT_REQUEST';
export const CREATE_BOT_ENDPOINT_SUCCESS = 'CREATE_BOT_ENDPOINT_SUCCESS';
export const CREATE_BOT_ENDPOINT_FAILURE = 'CREATE_BOT_ENDPOINT_FAILURE';

export const UPDATE_BOT_ENDPOINT_REQUEST = 'UPDATE_BOT_ENDPOINT_REQUEST';
export const UPDATE_BOT_ENDPOINT_SUCCESS = 'UPDATE_BOT_ENDPOINT_SUCCESS';
export const UPDATE_BOT_ENDPOINT_FAILURE = 'UPDATE_BOT_ENDPOINT_FAILURE';

export const DELETE_BOT_ENDPOINT_REQUEST = 'DELETE_BOT_ENDPOINT_REQUEST';
export const DELETE_BOT_ENDPOINT_SUCCESS = 'DELETE_BOT_ENDPOINT_SUCCESS';
export const DELETE_BOT_ENDPOINT_FAILURE = 'DELETE_BOT_ENDPOINT_FAILURE';

export const REFRESH_BOT_CLASSES_REQUEST = 'REFRESH_BOT_CLASSES_REQUEST';
export const REFRESH_BOT_CLASSES_SUCCESS = 'REFRESH_BOT_CLASSES_SUCCESS';
export const REFRESH_BOT_CLASSES_FAILURE = 'REFRESH_BOT_CLASSES_FAILURE';
