// Active Package
export const FETCH_ACTIVE_PACKAGE_REQUEST = 'FETCH_ACTIVE_PACKAGE_REQUEST'
export const FETCH_ACTIVE_PACKAGE_SUCCESS = 'FETCH_ACTIVE_PACKAGE_SUCCESS'
export const FETCH_ACTIVE_PACKAGE_FAILURE = 'FETCH_ACTIVE_PACKAGE_FAILURE'

// Buy Credits
export const BUY_CREDITS_REQUEST = 'BUY_CREDITS_REQUEST'
export const BUY_CREDITS_SUCCESS = 'BUY_CREDITS_SUCCESS'
export const BUY_CREDITS_FAILURE = 'BUY_CREDITS_FAILURE'

// Redeem Code
export const REDEEM_CODE_REQUEST = 'REDEEM_CODE_REQUEST'
export const REDEEM_CODE_SUCCESS = 'REDEEM_CODE_SUCCESS'
export const REDEEM_CODE_FAILURE = 'REDEEM_CODE_FAILURE'
export const CLEAR_REDEEM_RESULT = 'CLEAR_REDEEM_RESULT'

// History
export const FETCH_HISTORY_REQUEST = 'FETCH_HISTORY_REQUEST'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE'

// Cryptomus Deposit
export const CREATE_CRYPTOMUS_INVOICE_REQUEST = 'CREATE_CRYPTOMUS_INVOICE_REQUEST'
export const CREATE_CRYPTOMUS_INVOICE_SUCCESS = 'CREATE_CRYPTOMUS_INVOICE_SUCCESS'
export const CREATE_CRYPTOMUS_INVOICE_FAILURE = 'CREATE_CRYPTOMUS_INVOICE_FAILURE'
export const RESET_CRYPTOMUS_STATUS = 'RESET_CRYPTOMUS_STATUS'

// Cryptomus Payment Polling
export const POLL_CRYPTOMUS_STATUS_START = 'POLL_CRYPTOMUS_STATUS_START'
export const POLL_CRYPTOMUS_STATUS_STOP = 'POLL_CRYPTOMUS_STATUS_STOP'
export const POLL_CRYPTOMUS_STATUS_UPDATE = 'POLL_CRYPTOMUS_STATUS_UPDATE'
export const POLL_CRYPTOMUS_PAYMENT_DETAILS = 'POLL_CRYPTOMUS_PAYMENT_DETAILS'
