export const FETCH_DATABASE_STATS_REQUEST = 'FETCH_DATABASE_STATS_REQUEST'
export const FETCH_DATABASE_STATS_SUCCESS = 'FETCH_DATABASE_STATS_SUCCESS'
export const FETCH_DATABASE_STATS_FAILURE = 'FETCH_DATABASE_STATS_FAILURE'

export const BACKUP_COLLECTION_REQUEST = 'BACKUP_COLLECTION_REQUEST'
export const BACKUP_COLLECTION_SUCCESS = 'BACKUP_COLLECTION_SUCCESS'
export const BACKUP_COLLECTION_FAILURE = 'BACKUP_COLLECTION_FAILURE'
