export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const APPROVE_ORDER_REQUEST = 'APPROVE_ORDER_REQUEST';
export const APPROVE_ORDER_SUCCESS = 'APPROVE_ORDER_SUCCESS';
export const APPROVE_ORDER_FAILURE = 'APPROVE_ORDER_FAILURE';

export const REJECT_ORDER_REQUEST = 'REJECT_ORDER_REQUEST';
export const REJECT_ORDER_SUCCESS = 'REJECT_ORDER_SUCCESS';
export const REJECT_ORDER_FAILURE = 'REJECT_ORDER_FAILURE';
