export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE';

export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAILURE = 'CREATE_ROLE_FAILURE';

export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE = 'UPDATE_ROLE_FAILURE';

export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILURE = 'DELETE_ROLE_FAILURE';

export const FETCH_PERMISSION_USERS_REQUEST = 'FETCH_PERMISSION_USERS_REQUEST';
export const FETCH_PERMISSION_USERS_SUCCESS = 'FETCH_PERMISSION_USERS_SUCCESS';
export const FETCH_PERMISSION_USERS_FAILURE = 'FETCH_PERMISSION_USERS_FAILURE';

export const UPDATE_USER_ROLE_REQUEST = 'UPDATE_USER_ROLE_REQUEST';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const UPDATE_USER_ROLE_FAILURE = 'UPDATE_USER_ROLE_FAILURE';

export const FETCH_PERMISSIONS_LIST_REQUEST = 'FETCH_PERMISSIONS_LIST_REQUEST';
export const FETCH_PERMISSIONS_LIST_SUCCESS = 'FETCH_PERMISSIONS_LIST_SUCCESS';
export const FETCH_PERMISSIONS_LIST_FAILURE = 'FETCH_PERMISSIONS_LIST_FAILURE';
