// Stats
export const FETCH_REFERRAL_STATS_REQUEST = 'FETCH_REFERRAL_STATS_REQUEST'
export const FETCH_REFERRAL_STATS_SUCCESS = 'FETCH_REFERRAL_STATS_SUCCESS'
export const FETCH_REFERRAL_STATS_FAILURE = 'FETCH_REFERRAL_STATS_FAILURE'

// List
export const FETCH_REFERRAL_LIST_REQUEST = 'FETCH_REFERRAL_LIST_REQUEST'
export const FETCH_REFERRAL_LIST_SUCCESS = 'FETCH_REFERRAL_LIST_SUCCESS'
export const FETCH_REFERRAL_LIST_FAILURE = 'FETCH_REFERRAL_LIST_FAILURE'
