export const FETCH_BOT_ENDPOINTS_REQUEST = 'admin/upload-model/FETCH_BOT_ENDPOINTS_REQUEST'
export const FETCH_BOT_ENDPOINTS_SUCCESS = 'admin/upload-model/FETCH_BOT_ENDPOINTS_SUCCESS'
export const FETCH_BOT_ENDPOINTS_FAILURE = 'admin/upload-model/FETCH_BOT_ENDPOINTS_FAILURE'
